linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errname
    - exhaustive
    - godot
    - goimports
    - lll
    - usestdlibvars
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/nint8835/interruption-spotter

issues:
  exclude-rules:
    - path: 'pkg/server/static/fs.go'
      linters:
        # In CI the tailwind output won't be built, so linting will fail on the go:embed directive
        - typecheck
