// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type SpotInstanceStat struct {
	ID                     int64
	Region                 string
	OperatingSystem        string
	InstanceType           string
	InterruptionLevel      int64
	InterruptionLevelLabel string
	ObservedTime           time.Time
}
